[2023-12-12 04:09:44,776] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.11:5000 - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:44,781] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:44,783] INFO _log() L187   * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:47,812] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:09:47] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:48,645] ERROR inserir_doador() L222  Erro ao inserir dados: 'list' object has no attribute 'predict' - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L222 
[2023-12-12 04:09:48,646] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:09:48] "[35m[1mPOST /doador/inserir HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:58,015] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:09:58] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:09:58,326] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:09:58] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:12,063] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:12] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:12,329] ERROR inserir_doador() L222  Erro ao inserir dados: 'list' object has no attribute 'predict' - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L222 
[2023-12-12 04:10:12,330] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:12] "[35m[1mPOST /doador/inserir HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:20,190] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:20] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:20,499] ERROR inserir_doador() L222  Erro ao inserir dados: 'list' object has no attribute 'predict' - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L222 
[2023-12-12 04:10:20,500] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:20] "[35m[1mPOST /doador/inserir HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:47,215] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:47] "OPTIONS /doador/deletar/55555555555 HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:47,534] INFO deletar_doador() L240  Tentando excluir doador 55555555555 - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L240 
[2023-12-12 04:10:47,539] INFO deletar_doador() L242  doador 55555555555 excluído com sucesso - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L242 
[2023-12-12 04:10:47,539] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:47] "DELETE /doador/deletar/55555555555 HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:47,823] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:47] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:48,129] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:48] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:58,546] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:58] "OPTIONS /doador/deletar/22222222222 HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:58,812] INFO deletar_doador() L240  Tentando excluir doador 22222222222 - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L240 
[2023-12-12 04:10:58,816] INFO deletar_doador() L242  doador 22222222222 excluído com sucesso - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L242 
[2023-12-12 04:10:58,817] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:58] "DELETE /doador/deletar/22222222222 HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:59,396] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:59] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:10:59,700] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:10:59] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:11:26,736] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:11:26] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:11:27,004] ERROR inserir_doador() L222  Erro ao inserir dados: 'list' object has no attribute 'predict' - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L222 
[2023-12-12 04:11:27,004] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:11:27] "[35m[1mPOST /doador/inserir HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:12:55,325] INFO _log() L187   * Detected change in 'C:\\Users\\fmsco\\OneDrive\\Área de Trabalho\\Códigos Pós\\sprint 2\\red_flow\\backend\\schemas\\donator_schema.py', reloading - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:12:55,429] INFO _log() L187   * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:00,332] INFO _log() L187   * Detected change in 'C:\\Users\\fmsco\\OneDrive\\Área de Trabalho\\Códigos Pós\\sprint 2\\red_flow\\backend\\schemas\\donator_schema.py', reloading - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:00,452] INFO _log() L187   * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:02,781] INFO _log() L187   * Detected change in 'C:\\Users\\fmsco\\OneDrive\\Área de Trabalho\\Códigos Pós\\sprint 2\\red_flow\\backend\\schemas\\donator_schema.py', reloading - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:02,837] INFO _log() L187   * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:07,389] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:14:07] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:14:08,247] ERROR inserir_doador() L222  Erro ao inserir dados: 'list' object has no attribute 'predict' - call_trace=C:\Users\fmsco\OneDrive\Área de Trabalho\Códigos Pós\sprint 2\red_flow\backend\app.py L222 
[2023-12-12 04:14:08,248] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:14:08] "[35m[1mPOST /doador/inserir HTTP/1.1[0m" 500 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:02,325] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.11:5000 - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:02,326] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:02,329] INFO _log() L187   * Restarting with stat - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:07,342] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:16:07] "OPTIONS /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:08,186] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:16:08] "POST /doador/inserir HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:08,205] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:16:08] "[35m[1mGET /doador/exibir HTTP/1.1[0m" 202 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:16:24,664] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:16:24] "POST /swagger/novodoador HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:18:22,743] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:18:22] "[31m[1mPOST /swagger/novodoador HTTP/1.1[0m" 421 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:18:22,752] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:18:22] "[31m[1mPOST /swagger/novodoador HTTP/1.1[0m" 421 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
[2023-12-12 04:18:30,535] INFO _log() L187  127.0.0.1 - - [12/Dec/2023 04:18:30] "POST /swagger/novodoador HTTP/1.1" 200 - - call_trace=C:\Python311\Lib\site-packages\werkzeug\_internal.py L187 
